# Ubuntu upstart file at /etc/init/mms-agent.conf

description "MongoDB Monitoring Service (MMS) Agent"

pre-start script
mkdir -p /var/log/mms-agent/
end script

post-stop script
echo "$(date +'%Y-%m-%d %T,000') INFO mms-agent stopped" >> /var/log/mms-agent/agent.log
end script

start on runlevel [2345]
stop on runlevel [06]

exec nohup /usr/bin/env python /opt/mms-agent/agent.py >> /var/log/mms-agent/agent.log 2>&1
